FROM golang:1.22.5 as base

WORKDIR /app

COPY static/go.mod static/go.sum ./
 
RUN go mod download

COPY . .

RUN go build -o main .

# MULTI BUILD STAGE STARTS

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=base /app/main /app/main

COPY --from=base /app/static /app/static

EXPOSE 8080

ENTRYPOINT [ "./main" ]
